version: '3.8'

services:
  resume-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    container_name: resume-analyzer
    # restart: unless-stopped  # Uncomment for production
